#!/bin/bash

# Update the system
sudo yum update -y

# Install required packages
sudo yum install -y httpd php gcc glibc glibc-common gd gd-devel make net-snmp

# Download Nagios Core
cd /tmp
wget https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
tar -xzf nagios-4.4.6.tar.gz
cd nagioscore-nagios-4.4.6/

# Compile and install Nagios Core
./configure --with-httpd-conf=/etc/httpd/conf.d
make all
sudo make install
sudo make install-init
sudo make install-commandmode
sudo make install-config
sudo make install-webconf

# Create a Nagios user and set the password
sudo useradd nagios
sudo passwd nagios

# Add the Apache user to the Nagios group
sudo usermod -a -G nagios apache

# Download and install Nagios Plugins
cd /tmp
wget https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
tar -xzf release-2.3.3.tar.gz
cd nagios-plugins-release-2.3.3/
./tools/setup
./configure
make
sudo make install

# Start Apache and Nagios services
sudo systemctl start httpd
sudo systemctl enable httpd
sudo systemctl start nagios
sudo systemctl enable nagios

# Open necessary ports in the firewall
sudo firewall-cmd --zone=public --add-port=80/tcp --permanent
sudo firewall-cmd --reload

# Cleanup temporary files
cd /tmp
rm -rf nagios-4.4.6.tar.gz nagioscore-nagios-4.4.6 release-2.3.3.tar.gz nagios-plugins-release-2.3.3

# Access Nagios web interface
echo "Nagios installation completed. You can access the Nagios web interface at http://<your-server-IP>/nagios"
